### ISSUE TITLE
non endpoint functions

### ISSUE THREAD

**Issue by Faridalim** [a-luna/fastapi-redis-cache#32]
Can i use this cache for a non endpoint functions? Thank you..

**Comment by a-luna** [comment]
No, it expects an HTTP request and checks the method type in order to determine if the result should be cached. For regular functions, you can use the decorators from the built-in `functools` module:

- [`@lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache)
  - _available since 3.2_
- [`@cache`](https://docs.python.org/3/library/functools.html#functools.cache)
  - _available since 3.9_
- [`@cached_property`](https://docs.python.org/3/library/functools.html#functools.cached_property)
  - _available since 3.8_

However, all of these will only cache results while your program is running. If you are asking because you need to cache results **and** persist them, the package below looks like it could be what you need:

[python-redis-cache](https://github.com/taylorhakes/python-redis-cache)
